language: c

env:
  - LUA="Lua 5.1"
  - LUA="Lua 5.2"
  - LUA="LuaJIT 2.0"

before_install:
  - bash .travis_setup.sh

install:
  - sudo luarocks make rockspecs/argparse-scm-1.rockspec
  - sudo luarocks install busted

script:
  - busted spec
